Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -88,30 +88,27 @@ jobs:
           PUBLIC_SUFFIX_PATH=$(python -c "import whois, os; print(os.path.join(os.path.dirname(whois.__file__), 'data', 'public_suffix_list.dat'))")
           echo "::set-output name=path::$PUBLIC_SUFFIX_PATH"
 
-      - name: Build macOS App
-        run: |
-          # Entferne vorherige Builds
-          rm -rf build dist
-          
-          # Finde den Pfad zu public_suffix_list.dat aus dem vorherigen Schritt
-          PUBLIC_SUFFIX_PATH=${{ steps.find_public_suffix.outputs.path }}
-          
-          # Überprüfen, ob die Datei existiert
-          if [ ! -f "$PUBLIC_SUFFIX_PATH" ]; then
-            echo "Error: public_suffix_list.dat not found at $PUBLIC_SUFFIX_PATH"
-            exit 1
-          fi
-          
-          # Baue die App mit PyInstaller und füge die Daten-Datei hinzu
-          pyinstaller --windowed \
-            --icon=assets/logo.icns \
-            --hidden-import PyQt6.QtWebEngineCore \
-            --hidden-import PyQt6.QtWebEngineWidgets \
-            --add-binary "/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib:." \
-            --add-binary "/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib:." \
-            --add-data "/Applications/VLC.app/Contents/MacOS/plugins:plugins" \
-            --add-data "$PUBLIC_SUFFIX_PATH:whois/data" \
-            TMP-Networks-Browser-Mini.py
+- name: Build macOS App
+  run: |
+    # Entferne vorherige Builds
+    rm -rf build dist
+    
+    # Überprüfen, ob die Datei existiert
+    if [ ! -f "$PUBLIC_SUFFIX_PATH" ]; then
+      echo "Error: public_suffix_list.dat not found at $PUBLIC_SUFFIX_PATH"
+      exit 1
+    fi
+    
+    # Baue die App mit PyInstaller und füge die Daten-Datei hinzu
+    pyinstaller --windowed \
+      --icon=assets/logo.icns \
+      --hidden-import PyQt6.QtWebEngineCore \
+      --hidden-import PyQt6.QtWebEngineWidgets \
+      --add-binary "/Applications/VLC.app/Contents/MacOS/lib/libvlc.dylib:." \
+      --add-binary "/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib:." \
+      --add-data "/Applications/VLC.app/Contents/MacOS/plugins:plugins" \
+      --add-data "$PUBLIC_SUFFIX_PATH:whois/data" \
+      TMP-Networks-Browser-Mini.py
 
       - name: List dist Directory
         run: |
